### ISSUE TITLE
Hardwired .wiki File Extension?

### ISSUE THREAD

**Issue by madranet** [Dessyreqt/awiki#2]
I'm not having much luck getting your extension to recognise an existing Vimwiki. It seems you've hard-wired the extension to only use/recognise files ending with a `.wiki` extension. My Vimwiki files all use the `.md` extension. 

Any chance you could provide an option for the user to specify the file extension to be used?  I'd like to keep my wiki accessible from both Atom and Vim.

**Comment by Dessyreqt** [comment]
Awiki actually uses the grammar of the file to set whether or not it should enable the linking functionality. You can test this by setting the grammar of one of your wiki files to "Awiki" and testing links that way.

I'd recommend downloading the [file-types](https://atom.io/packages/file-types) extension so that you can define a custom grammar for `.md` files.

Here's what you might add to your config.cson:

``` cson
'file-types':
  'md': 'source.wiki'
```

**Comment by obedm503** [comment]
It still navigates to `.wiki` files on `<Alt>-<Enter>`
